using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SM.Bible.Formats
{
    /// <summary>
    /// This code is based on the Python code by Chris Little https://github.com/chrislit/usfm2osis
    /// which is available under GNU General Public License v3.0.
    /// </summary>
    public class Constants
    {
        public static string USFM_VERSION = "2.35";  // http://ubs-icap.org/chm/usfm/2.35/index.html

        public static string[] SIMPLE_TAGS =
        {
        "\\id",
        "\\ide",
        "\\sts",
        "\\rem",
        "\\h",
        "\\toc1",
        "\\toc2",
        "\\toc3",
        "\\ip",
        "\\ipi",
        "\\im",
        "\\imi",
        "\\ipq",
        "\\imq",
        "\\ipr",
        "\\ib",
        "\\ili",
        "\\iot",
        "\\ior",
        "\\ior*",
        "\\iex",
        "\\iqt",
        "\\iqt*",
        "\\imte",
        "\\ie",
        "\\mr",
        "\\sr",
        "\\r",
        "\\rq",
        "\\rq*",
        "\\d",
        "\\sp",
        "\\c",
        "\\ca",
        "\\ca*",
        "\\cl",
        "\\cp",
        "\\cd",
        "\\v",
        "\\va",
        "\\va*",
        "\\vp",
        "\\vp*",
        "\\p",
        "\\m",
        "\\pmo",
        "\\pm",
        "\\pmc",
        "\\pmr",
        "\\mi",
        "\\nb",
        "\\cls",
        "\\pc",
        "\\pr",
        "\\b",
        "\\qr",
        "\\qc",
        "\\qs",
        "\\qs*",
        "\\qa",
        "\\qac",
        "\\qac*",
        "\\tr",
        "\\f",
        "\\f*",
        "\\fe",
        "\\fe*",
        "\\fr",
        "\\fk",
        "\\fq",
        "\\fqa",
        "\\fl",
        "\\fp",
        "\\fv",
        "\\ft",
        "\\fdc",
        "\\fdc*",
        "\\fm",
        "\\fm*",
        "\\x",
        "\\x*",
        "\\xo",
        "\\xk",
        "\\xq",
        "\\xt",
        "\\xot",
        "\\xot*",
        "\\xnt",
        "\\xnt*",
        "\\xdc",
        "\\xdc*",
        "\\add",
        "\\add*",
        "\\bk",
        "\\bk*",
        "\\dc",
        "\\dc*",
        "\\k",
        "\\k*",
        "\\lit",
        "\\nd",
        "\\nd*",
        "\\ord",
        "\\ord*",
        "\\pn",
        "\\pn*",
        "\\qt",
        "\\qt*",
        "\\sig",
        "\\sig*",
        "\\sls",
        "\\sls*",
        "\\tl",
        "\\tl*",
        "\\wj",
        "\\wj*",
        "\\em",
        "\\em*",
        "\\bd",
        "\\bd*",
        "\\it",
        "\\it*",
        "\\bdit",
        "\\bdit*",
        "\\no",
        "\\no*",
        "\\sc",
        "\\sc*",
        "\\pb",
        "\\fig",
        "\\fig*",
        "\\ndx",
        "\\ndx*",
        "\\pro",
        "\\pro*",
        "\\w",
        "\\w*",
        "\\wg",
        "\\wg*",
        "\\wh",
        "\\wh*",
        "\\periph",
        "\\ef",
        "\\ef*",
        "\\ex",
        "\\ex*",
        "\\esb",
        "\\esbe",
        "\\cat",
        "\\z"
        };

        public static string[] DIGIT_TAGS =
        {
        "\\imt",
        "\\is",
        "\\iq",
        "\\io",
        "\\mt",
        "\\mte",
        "\\ms",
        "\\s",
        "\\pi",
        "\\li",
        "\\ph",
        "\\q",
        "\\qm",
        "\\th",
        "\\thr",
        "\\tc",
        "\\tcr",

        };

    }
}
